import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { supabase } from '@/lib/supabase';
import { getTrip, listTripMembers, type Trip, type TripMemberWithProfile } from '@/lib/trips';
import { filterAndSortItems, type ItineraryItem } from '@/lib/itinerary';
import { deleteItineraryItem, listItineraryItems, saveItineraryItem } from '@/lib/itinerary-api';
import { DayTabs } from '@/components/DayTabs';
import { TripMap } from '@/components/TripMap';
import { ItineraryTimeline } from '@/components/ItineraryTimeline';
import { ItineraryItemModal } from '@/components/ItineraryItemModal';
import { InviteTripModal } from '@/components/InviteTripModal';

export default function TripDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const tripId = Array.isArray(id) ? id[0] : id; const { width } = useWindowDimensions();
  const [trip, setTrip] = useState<Trip | null>(null); const [members, setMembers] = useState<TripMemberWithProfile[]>([]); const [items, setItems] = useState<ItineraryItem[]>([]); const [userId, setUserId] = useState(''); const [day, setDay] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<ItineraryItem | null>(null); const [inviteVisible, setInviteVisible] = useState(false);
  const days = useMemo(() => { const values = Array.from(new Set(items.map((item) => item.day_number))).sort((a, b) => a - b); return values.length ? values : [1]; }, [items]);
  async function load() { if (!tripId) return; setLoading(true); setError(''); try { const [{ data: auth }, tripData, memberData, itemData] = await Promise.all([supabase.auth.getUser(), getTrip(tripId), listTripMembers(tripId), listItineraryItems(tripId)]); setUserId(auth.user?.id ?? ''); setTrip(tripData); setMembers(memberData); setItems(itemData); } catch (e: any) { console.error('[TripDetail] load failed', e); setError(e?.message ?? '無法載入行程資料。'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [tripId]);
  if (loading) return <View style={styles.center}><ActivityIndicator color="#2563eb" /></View>;
  if (!trip) return <View style={styles.center}><Text style={styles.error}>{error || '找不到此行程。'}</Text></View>;
  const visible = filterAndSortItems(items, day);
  return <View style={styles.container}><View style={styles.header}><View><Pressable onPress={() => { if (router.canGoBack()) router.back(); else router.replace('/'); }}><Text style={styles.back}>‹ 返回我的行程</Text></Pressable><Text style={styles.title}>{trip.title}</Text><Text style={styles.destination}>{trip.destination} · {trip.start_date} ～ {trip.end_date}</Text></View><View style={styles.headerMembers}>{members.slice(0, 4).map((member, index) => <View key={member.user_id} style={[styles.avatar, { marginLeft: index ? -9 : 0 }]}><Text style={styles.avatarText}>{(member.profile?.display_name || member.user_id).slice(0, 1).toUpperCase()}</Text></View>)}<Pressable style={styles.inviteButton} onPress={() => setInviteVisible(true)}><Text style={styles.inviteText}>＋ 邀請</Text></Pressable></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<DayTabs days={days} selected={day} onChange={setDay} /><View style={[styles.columns, width >= 800 && styles.columnsWide]}><ScrollView style={styles.timelinePane} contentContainerStyle={styles.paneContent}><Text style={styles.paneTitle}>Day {day} 行程</Text><ItineraryTimeline items={visible} onEdit={(item) => { setEditing(item); setModal(true); }} onDelete={async (item) => { try { await deleteItineraryItem(item.id); await load(); } catch (e: any) { setError(e?.message ?? '刪除失敗。'); } }} /></ScrollView><View style={styles.mapPane}><TripMap items={items} day={day} /></View></View><Pressable style={styles.fab} onPress={() => { setEditing(null); setModal(true); }}><Text style={styles.fabText}>＋ 新增景點／活動</Text></Pressable><ItineraryItemModal visible={modal} item={editing} day={day} tripId={tripId} userId={userId} onClose={() => setModal(false)} onSave={async (data) => { try { await saveItineraryItem(data); setModal(false); await load(); } catch (e: any) { setError(e?.message ?? '儲存失敗。'); } }} onDelete={editing ? async () => { await deleteItineraryItem(editing.id); await load(); } : undefined} /><InviteTripModal visible={inviteVisible} inviteCode={trip.invite_code} onClose={() => setInviteVisible(false)} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#f8fafc', padding: 22, paddingTop: 30 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 14 }, back: { color: '#2563eb', fontWeight: '700', marginBottom: 9 }, title: { fontSize: 30, fontWeight: '800', color: '#0f172a' }, destination: { color: '#64748b', fontSize: 16 }, headerMembers: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#dbeafe', borderWidth: 2, borderColor: '#f8fafc', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#1d4ed8', fontWeight: '800' }, inviteButton: { marginLeft: 12, borderRadius: 13, backgroundColor: '#e0e7ff', paddingHorizontal: 12, paddingVertical: 9 }, inviteText: { color: '#3730a3', fontWeight: '700' }, columns: { flex: 1, gap: 14 }, columnsWide: { flexDirection: 'row' }, timelinePane: { flex: 1, backgroundColor: 'white', borderRadius: 18 }, paneContent: { padding: 16, paddingBottom: 100 }, paneTitle: { fontSize: 18, fontWeight: '800', marginBottom: 4 }, mapPane: { flex: 1, minHeight: 280, borderRadius: 18, overflow: 'hidden' }, fab: { position: 'absolute', right: 34, bottom: 24, borderRadius: 24, paddingHorizontal: 18, paddingVertical: 14, backgroundColor: '#2563eb' }, fabText: { color: 'white', fontWeight: '700' }, error: { color: '#b91c1c', marginBottom: 8 } });
