import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { supabase } from '@/lib/supabase';
import { getTrip, listTripMembers, updateTrip, type Trip, type TripMemberWithProfile } from '@/lib/trips';
import { filterAndSortItems, type ItineraryItem } from '@/lib/itinerary';
import { tripDayNumbers } from '@/lib/trip-dates';
import { deleteItineraryItem, listItineraryItems, saveItineraryItem, updateItineraryItemsOrder } from '@/lib/itinerary-api';
import { calculateBalances, deleteExpense, listExpenses, saveExpense, type Expense } from '@/lib/expenses-api';
import { DayTabs } from '@/components/DayTabs'; import { TripMap } from '@/components/TripMap'; import { ItineraryTimeline } from '@/components/ItineraryTimeline'; import { ItineraryItemModal } from '@/components/ItineraryItemModal'; import { InviteTripModal } from '@/components/InviteTripModal'; import { ExpenseList } from '@/components/ExpenseList'; import { ExpenseModal } from '@/components/ExpenseModal'; import { SettlementCard } from '@/components/SettlementCard'; import { PackingPanel } from '@/components/PackingPanel'; import { DocumentsPanel } from '@/components/DocumentsPanel'; import { TripSettingsModal } from '@/components/TripSettingsModal';

type Tab = 'timeline' | 'expenses' | 'packing' | 'documents';
const tabs: { value: Tab; label: string }[] = [{ value: 'timeline', label: '行程時間軸' }, { value: 'expenses', label: '💰 旅費分帳' }, { value: 'packing', label: '🧳 打包清單' }, { value: 'documents', label: '📄 憑證管理' }];

export default function TripDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { width } = useWindowDimensions(); const tripId = Array.isArray(id) ? id[0] : id;
  const [trip, setTrip] = useState<Trip | null>(null); const [members, setMembers] = useState<TripMemberWithProfile[]>([]); const [items, setItems] = useState<ItineraryItem[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [userId, setUserId] = useState(''); const [day, setDay] = useState(1); const [tab, setTab] = useState<Tab>('timeline'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [itemModal, setItemModal] = useState(false); const [expenseModal, setExpenseModal] = useState(false); const [editingItem, setEditingItem] = useState<ItineraryItem | null>(null); const [editingExpense, setEditingExpense] = useState<Expense | null>(null); const [inviteVisible, setInviteVisible] = useState(false); const [settingsVisible, setSettingsVisible] = useState(false);
  const days = useMemo(() => trip ? tripDayNumbers(trip.start_date, trip.end_date) : [1], [trip]);
  const memberName = (memberId: string) => members.find((member) => member.user_id === memberId)?.profile?.display_name || memberId.slice(0, 8);
  async function reorderItems(order: { id: string; position: number }[]) { const previous = items; const positions = new Map(order.map((entry) => [entry.id, entry.position])); setItems((current) => current.map((item) => positions.has(item.id) ? { ...item, position: positions.get(item.id)! } : item)); try { await updateItineraryItemsOrder(order); } catch (cause) { setItems(previous); throw cause; } }
  async function load() { if (!tripId) return; setLoading(true); setError(''); try { const [{ data: auth }, tripData, memberData, itemData, expenseData] = await Promise.all([supabase.auth.getUser(), getTrip(tripId), listTripMembers(tripId), listItineraryItems(tripId), listExpenses(tripId)]); setUserId(auth.user?.id ?? ''); setTrip(tripData); setMembers(memberData); setItems(itemData); setExpenses(expenseData); } catch (cause: any) { console.error('[TripDetail] load failed', cause); setError(cause?.message ?? '無法載入行程資料。'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [tripId]);
  if (loading) return <View style={styles.center}><ActivityIndicator color="#2563eb" /></View>;
  if (!trip) return <View style={styles.center}><Text style={styles.error}>{error || '找不到此行程。'}</Text></View>;
  const visibleItems = filterAndSortItems(items, day);
  return <View style={styles.container}>
    <View style={styles.header}><View><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace('/')}><Text style={styles.back}>‹ 返回我的行程</Text></Pressable><Text style={styles.title}>{trip.title}</Text><Text style={styles.destination}>{trip.destination} · {trip.start_date} ～ {trip.end_date}</Text></View><View style={styles.headerMembers}>{members.slice(0, 4).map((member, index) => <View key={member.user_id} style={[styles.avatar, { marginLeft: index ? -9 : 0 }]}><Text style={styles.avatarText}>{(member.profile?.display_name || member.user_id)[0].toUpperCase()}</Text></View>)}<Pressable style={styles.inviteButton} onPress={() => setInviteVisible(true)}><Text style={styles.inviteText}>＋ 邀請</Text></Pressable></View></View>
    {error ? <Text style={styles.error}>{error}</Text> : null}
    {trip.created_by === userId ? <Pressable style={styles.settingsButton} onPress={() => setSettingsVisible(true)}><Text style={styles.settingsText}>⚙️ 行程設定</Text></Pressable> : null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={[styles.tabScroller, { height: 52, maxHeight: 52, flexGrow: 0 }]} contentContainerStyle={[styles.tabs, { alignItems: 'center', gap: 4 }]}>{tabs.map((item) => <Pressable key={item.value} style={[styles.tab, { height: 44, minWidth: 136, flex: 0, flexGrow: 0, flexShrink: 0, justifyContent: 'center', paddingHorizontal: 14 }, tab === item.value && styles.activeTab]} onPress={() => setTab(item.value)}><Text numberOfLines={1} style={tab === item.value ? styles.activeText : styles.tabText}>{item.label}</Text></Pressable>)}</ScrollView>
    {tab === 'timeline' && <><DayTabs days={days} selected={day} onChange={setDay} /><View style={[styles.columns, width >= 800 && styles.columnsWide]}><ScrollView style={styles.timelinePane} contentContainerStyle={styles.paneContent}><Text style={styles.paneTitle}>Day {day} 行程</Text><ItineraryTimeline items={visibleItems} scheduleContext={{ tripStartDate: trip.start_date, dayNumber: day, defaultDepartureTime: trip.default_departure_time }} onEdit={(item) => { setEditingItem(item); setItemModal(true); }} onDelete={async (item) => { await deleteItineraryItem(item.id); await load(); }} onReorder={reorderItems} /></ScrollView><View style={styles.mapPane}><TripMap items={items} day={day} /></View></View><Pressable style={styles.fab} onPress={() => { setEditingItem(null); setItemModal(true); }}><Text style={styles.buttonText}>＋ 新增景點／活動</Text></Pressable></>}
    {tab === 'expenses' && <ScrollView contentContainerStyle={styles.panel}><SettlementCard settlements={calculateBalances(expenses)} labelFor={memberName} /><ExpenseList expenses={expenses} members={members} onEdit={(expense) => { setEditingExpense(expense); setExpenseModal(true); }} onDelete={async (expense) => { await deleteExpense(expense.id); await load(); }} /><Pressable style={styles.primary} onPress={() => { setEditingExpense(null); setExpenseModal(true); }}><Text style={styles.buttonText}>＋ 新增旅費</Text></Pressable></ScrollView>}
    {tab === 'packing' && <PackingPanel tripId={tripId} members={members} />}
    {tab === 'documents' && <DocumentsPanel tripId={tripId} userId={userId} />}
    <ItineraryItemModal visible={itemModal} item={editingItem} day={day} tripId={tripId} userId={userId} onClose={() => setItemModal(false)} onSave={async (data) => { await saveItineraryItem(data); setItemModal(false); await load(); }} onDelete={editingItem ? async () => { await deleteItineraryItem(editingItem.id); await load(); } : undefined} />
    <ExpenseModal visible={expenseModal} tripId={tripId} expense={editingExpense} members={members} userId={userId} onClose={() => setExpenseModal(false)} onSave={async (expense, splits) => { await saveExpense(expense, splits); setExpenseModal(false); await load(); }} />
    <InviteTripModal visible={inviteVisible} inviteCode={trip.invite_code} onClose={() => setInviteVisible(false)} />
    <TripSettingsModal visible={settingsVisible} departureTime={trip.default_departure_time} onClose={() => setSettingsVisible(false)} onSave={async (defaultDepartureTime) => { const updated = await updateTrip(trip.id, { default_departure_time: defaultDepartureTime }); setTrip(updated); }} />
  </View>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#f8fafc', padding: 22, paddingTop: 30 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 14 }, back: { color: '#2563eb', fontWeight: '700', marginBottom: 9 }, title: { fontSize: 30, fontWeight: '800', color: '#0f172a' }, destination: { color: '#64748b' }, headerMembers: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#dbeafe', borderWidth: 2, borderColor: '#f8fafc', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#1d4ed8', fontWeight: '800' }, inviteButton: { marginLeft: 12, borderRadius: 13, backgroundColor: '#e0e7ff', paddingHorizontal: 12, paddingVertical: 9 }, inviteText: { color: '#3730a3', fontWeight: '700' }, settingsButton: { alignSelf: 'flex-start', marginBottom: 8, borderRadius: 12, backgroundColor: '#e0e7ff', paddingHorizontal: 12, paddingVertical: 8 }, settingsText: { color: '#3730a3', fontWeight: '700' }, tabScroller: { flexGrow: 0, marginBottom: 7 }, tabs: { minWidth: '100%', flexDirection: 'row', backgroundColor: '#e2e8f0', borderRadius: 13, padding: 4 }, tab: { minWidth: 130, flex: 1, alignItems: 'center', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10 }, activeTab: { backgroundColor: 'white' }, tabText: { color: '#64748b', fontWeight: '700' }, activeText: { color: '#1d4ed8', fontWeight: '800' }, columns: { flex: 1, gap: 14 }, columnsWide: { flexDirection: 'row' }, timelinePane: { flex: 1, backgroundColor: 'white', borderRadius: 18 }, paneContent: { padding: 16, paddingBottom: 100 }, paneTitle: { fontSize: 18, fontWeight: '800' }, mapPane: { flex: 1, minHeight: 280, borderRadius: 18, overflow: 'hidden' }, panel: { paddingBottom: 100, paddingTop: 8 }, primary: { alignSelf: 'center', backgroundColor: '#2563eb', borderRadius: 13, paddingHorizontal: 20, paddingVertical: 13, marginTop: 18 }, fab: { position: 'absolute', right: 34, bottom: 24, borderRadius: 24, paddingHorizontal: 18, paddingVertical: 14, backgroundColor: '#2563eb' }, buttonText: { color: 'white', fontWeight: '800' }, error: { color: '#b91c1c', marginBottom: 8 } });
