import { Link, useRouter } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { FlatList, ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';
import { supabase } from '@/lib/supabase';
import { createTrip, listTripMembers, listTrips, type Trip, type TripMemberWithProfile } from '@/lib/trips';
import { CreateTripModal } from '@/components/CreateTripModal';
import { InviteTripModal } from '@/components/InviteTripModal';
import { PuppyMascot } from '@/components/PuppyMascot';
import { clearOfflineCache } from '@/lib/offline-cache';

function daysUntil(date: string) { const diff = Math.ceil((new Date(`${date}T00:00:00`).getTime() - Date.now()) / 86400000); return diff > 0 ? `離出發還有 ${diff} 天` : diff === 0 ? '今天出發' : '旅程進行中'; }
export default function HomeScreen() {
  const router = useRouter(); const [trips, setTrips] = useState<Trip[]>([]); const [members, setMembers] = useState<Record<string, TripMemberWithProfile[]>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [createVisible, setCreateVisible] = useState(false); const [joinVisible, setJoinVisible] = useState(false); const [userId, setUserId] = useState('');
  async function load() { setLoading(true); setError(''); try { const [{ data: auth }, rows] = await Promise.all([supabase.auth.getUser(), listTrips()]); setUserId(auth.user?.id ?? ''); setTrips(rows ?? []); const result = await Promise.all((rows ?? []).map(async (trip) => [trip.id, await listTripMembers(trip.id)] as const)); setMembers(Object.fromEntries(result)); } catch (e: any) { console.error('[HomeScreen] list trips failed', e); setError(e?.message ?? '無法載入行程。'); } finally { setLoading(false); } }
  async function signOut() { await clearOfflineCache(); await supabase.auth.signOut(); }
  useEffect(() => { load(); }, []);
  if (loading) return <View style={styles.center}><PuppyMascot puppy="-5" size={72} accessibilityLabel="載入中" /><Text style={styles.loadingText}>載入行程中…</Text></View>;
  return <View style={styles.container}><View style={styles.header}><View style={styles.brand}><PuppyMascot puppy="-1" size={72} accessibilityLabel="出遊由起來" /><View><Text style={styles.eyebrow}>TRAVEL PLANNER</Text><Text style={styles.title}>我的行程</Text></View></View><View style={styles.actions}><Pressable onPress={() => setJoinVisible(true)}><Text style={styles.link}>加入行程</Text></Pressable><Pressable onPress={() => void signOut()}><Text style={styles.link}>登出</Text></Pressable></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}{!error && trips.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>準備好下一趟旅程了嗎？</Text><Text style={styles.muted}>建立行程，和旅伴一起開始規劃。</Text><Pressable style={styles.primary} onPress={() => setCreateVisible(true)}><Text style={styles.white}>＋ 新增行程</Text></Pressable></View> : <FlatList contentContainerStyle={styles.list} data={trips} keyExtractor={(x) => x.id} renderItem={({ item }) => <Link href={`/trips/${item.id}`} asChild><Pressable style={styles.card}><ImageBackground source={{ uri: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?w=1200' }} imageStyle={styles.coverImage} style={styles.cover}><View style={styles.overlay}><Text style={styles.countdown}>{daysUntil(item.start_date)}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardDestination}>{item.destination}</Text></View></ImageBackground><View style={styles.cardInfo}><Text style={styles.date}>{item.start_date} ～ {item.end_date}</Text><View style={styles.avatarGroup}>{(members[item.id] ?? []).slice(0, 4).map((member, index) => <View key={member.user_id} style={[styles.avatar, { marginLeft: index ? -9 : 0 }]}><Text style={styles.avatarText}>{(member.profile?.display_name || member.user_id).slice(0, 1).toUpperCase()}</Text></View>)}<Text style={styles.memberCount}>{members[item.id]?.length ?? 0} 位旅伴</Text></View></View></Pressable></Link>} ListFooterComponent={<Pressable style={styles.secondary} onPress={() => setCreateVisible(true)}><Text style={styles.secondaryText}>＋ 新增另一個行程</Text></Pressable>} />}{!error && <CreateTripModal visible={createVisible} userId={userId} onClose={() => setCreateVisible(false)} onCreate={async (input) => { await createTrip(input); setCreateVisible(false); await load(); }} />}<InviteTripModal visible={joinVisible} onClose={() => setJoinVisible(false)} onJoined={(id) => router.push(`/trips/${id}`)} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#f8fafc', paddingHorizontal: 22, paddingTop: 32 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' }, loadingText: { color: '#64748b', marginTop: 10 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 22 }, brand: { flexDirection: 'row', alignItems: 'center', gap: 8 }, eyebrow: { fontSize: 11, letterSpacing: 2, color: '#64748b', fontWeight: '700' }, title: { fontSize: 32, color: '#0f172a', fontWeight: '800', marginTop: 3 }, actions: { flexDirection: 'row', gap: 13 }, link: { color: '#2563eb', fontWeight: '700' }, list: { gap: 16, paddingBottom: 40 }, card: { borderRadius: 22, backgroundColor: 'white', overflow: 'hidden', shadowColor: '#0f172a', shadowOpacity: 0.1, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 4 }, cover: { height: 190, justifyContent: 'flex-end' }, coverImage: { borderTopLeftRadius: 22, borderTopRightRadius: 22 }, overlay: { padding: 20, backgroundColor: 'rgba(15,23,42,.35)' }, countdown: { alignSelf: 'flex-start', color: 'white', backgroundColor: '#2563eb', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, fontWeight: '700', marginBottom: 10 }, cardTitle: { color: 'white', fontSize: 25, fontWeight: '800' }, cardDestination: { color: '#e2e8f0', fontSize: 15, marginTop: 3 }, cardInfo: { padding: 16, gap: 11 }, date: { color: '#64748b', fontSize: 14 }, avatarGroup: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#dbeafe', borderWidth: 2, borderColor: 'white', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#1d4ed8', fontWeight: '800' }, memberCount: { marginLeft: 8, color: '#64748b', fontSize: 13 }, empty: { alignItems: 'center', padding: 36, gap: 9, backgroundColor: 'white', borderRadius: 22 }, emptyTitle: { fontSize: 20, fontWeight: '800', color: '#0f172a' }, muted: { color: '#64748b', marginBottom: 10 }, primary: { backgroundColor: '#2563eb', borderRadius: 13, paddingHorizontal: 20, paddingVertical: 13 }, secondary: { alignSelf: 'center', padding: 12 }, secondaryText: { color: '#2563eb', fontWeight: '700' }, white: { color: 'white', fontWeight: '800' }, error: { color: '#b91c1c', marginBottom: 12 } });
