import { Link } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { supabase } from '@/lib/supabase';
import { createTrip, listTrips, type Trip } from '@/lib/trips';
import { CreateTripModal } from '@/components/CreateTripModal';

export default function HomeScreen() {
  const [trips, setTrips] = useState<Trip[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(false); const [userId, setUserId] = useState('');
  async function load() { setLoading(true); setError(''); try { const [{ data: auth }, rows] = await Promise.all([supabase.auth.getUser(), listTrips()]); setUserId(auth.user?.id ?? ''); setTrips(rows ?? []); } catch (e: any) { console.error('[HomeScreen] list trips failed', e); setError(e.message ?? '無法載入行程。'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  if (loading) return <View style={styles.center}><ActivityIndicator /></View>;
  return <View style={styles.container}><View style={styles.header}><Text style={styles.title}>我的行程</Text><Pressable onPress={() => supabase.auth.signOut()}><Text style={styles.link}>登出</Text></Pressable></View>{error ? <Text style={styles.error}>{error}</Text> : null}{!error && trips.length === 0 ? <View style={styles.empty}><Text>目前還沒有行程</Text><Pressable style={styles.createButton} onPress={() => setModal(true)}><Text style={styles.white}>＋ 新增行程</Text></Pressable></View> : null}<FlatList data={trips} keyExtractor={(x) => x.id} renderItem={({ item, index }) => <Link href={`/trips/${item.id}`} asChild><Pressable style={index === 0 ? styles.card : styles.row}><Text style={styles.tripTitle}>{item.title}</Text><Text>{item.destination} · {item.start_date} 至 {item.end_date}</Text></Pressable></Link>} ListFooterComponent={trips.length > 0 ? <Pressable style={styles.createButton} onPress={() => setModal(true)}><Text style={styles.white}>＋ 新增行程</Text></Pressable> : null} /><CreateTripModal visible={modal} userId={userId} onClose={() => setModal(false)} onCreate={async (input) => { await createTrip(input); await load(); }} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, padding: 24, gap: 16, backgroundColor: '#f7f9fc' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 30, fontWeight: '700' }, empty: { alignItems: 'center', gap: 16, padding: 30 }, card: { padding: 20, borderRadius: 18, backgroundColor: '#dbeafe', gap: 8, marginBottom: 12 }, row: { padding: 16, backgroundColor: 'white', borderRadius: 12, marginBottom: 8 }, tripTitle: { fontSize: 18, fontWeight: '600' }, error: { color: '#b91c1c' }, link: { color: '#2563eb', fontWeight: '600' }, createButton: { alignSelf: 'center', backgroundColor: '#2563eb', borderRadius: 10, paddingHorizontal: 18, paddingVertical: 13 }, white: { color: 'white', fontWeight: '700' } });
