import React, { useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

export function CreateTripModal({ visible, userId, onClose, onCreate }: { visible: boolean; userId: string; onClose: () => void; onCreate: (input: { title: string; destination: string; start_date: string; end_date: string; created_by: string }) => Promise<void> }) {
  const [title, setTitle] = useState(''); const [destination, setDestination] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [busy, setBusy] = useState(false);
  async function submit() { if (!title.trim() || !destination.trim() || !start || !end) return Alert.alert('請填寫完整行程資料'); if (end < start) return Alert.alert('結束日期不可早於開始日期'); setBusy(true); try { await onCreate({ title: title.trim(), destination: destination.trim(), start_date: start, end_date: end, created_by: userId }); setTitle(''); setDestination(''); setStart(''); setEnd(''); onClose(); } catch (e: any) { Alert.alert('建立行程失敗', e.message ?? '請稍後再試'); } finally { setBusy(false); } }
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={styles.container}><Text style={styles.title}>新增行程</Text><TextInput style={styles.input} placeholder="行程名稱" value={title} onChangeText={setTitle} /><TextInput style={styles.input} placeholder="目的地" value={destination} onChangeText={setDestination} /><TextInput style={styles.input} placeholder="開始日期 YYYY-MM-DD" value={start} onChangeText={setStart} /><TextInput style={styles.input} placeholder="結束日期 YYYY-MM-DD" value={end} onChangeText={setEnd} /><View style={styles.actions}><Pressable onPress={onClose}><Text>取消</Text></Pressable><Pressable style={styles.save} onPress={submit} disabled={busy}><Text style={styles.white}>{busy ? '建立中…' : '建立行程'}</Text></Pressable></View></View></Modal>;
}
const styles = StyleSheet.create({ container: { marginTop: 'auto', padding: 24, gap: 14, backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20 }, title: { fontSize: 24, fontWeight: '700' }, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 20 }, save: { backgroundColor: '#2563eb', borderRadius: 10, padding: 13 }, white: { color: 'white', fontWeight: '700' } });
