import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { ItineraryItem } from '@/lib/itinerary';
const icons: Record<string, string> = { spot: '📍', food: '🍜', hotel: '🛏️', flight: '✈️', trail: '🥾', outdoor: '🌿' };
export function ItineraryTimeline({ items, onEdit, onDelete }: { items: ItineraryItem[]; onEdit: (item: ItineraryItem) => void; onDelete: (item: ItineraryItem) => void }) {
  if (!items.length) return <View style={styles.empty}><Text style={styles.emptyIcon}>🗺️</Text><Text style={styles.emptyText}>這天還沒有安排景點</Text></View>;
  return <View>{items.map((item, index) => <View key={item.id} style={styles.row}><View style={styles.rail}>{index < items.length - 1 && <View style={styles.line} />}<View style={styles.dot} /></View><View style={styles.card}><View style={styles.cardHeader}><Text style={styles.time}>{item.time ?? '彈性時間'}</Text><Text style={styles.category}>{icons[item.category] ?? '📌'} {item.category}</Text></View><Text style={styles.name}>{item.location_name}</Text>{item.duration_minutes ? <Text style={styles.duration}>⏱ 停留 {item.duration_minutes} 分鐘</Text> : null}{item.address ? <Text style={styles.address}>{item.address}</Text> : null}{item.notes ? <Text style={styles.notes}>{item.notes}</Text> : null}<View style={styles.actions}><Pressable onPress={() => onEdit(item)}><Text style={styles.edit}>編輯</Text></Pressable><Pressable onPress={() => onDelete(item)}><Text style={styles.delete}>刪除</Text></Pressable></View></View></View>)}</View>;
}
const styles = StyleSheet.create({ empty: { padding: 38, alignItems: 'center', gap: 8 }, emptyIcon: { fontSize: 28 }, emptyText: { color: '#64748b' }, row: { flexDirection: 'row', minHeight: 130 }, rail: { width: 24, alignItems: 'center' }, line: { position: 'absolute', top: 18, bottom: 0, width: 2, backgroundColor: '#dbeafe' }, dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#2563eb', borderWidth: 3, borderColor: '#dbeafe', zIndex: 1 }, card: { flex: 1, marginBottom: 12, padding: 14, borderRadius: 15, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', gap: 5 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, time: { color: '#2563eb', fontWeight: '800' }, category: { color: '#64748b', fontSize: 12 }, name: { color: '#0f172a', fontSize: 18, fontWeight: '800' }, duration: { color: '#475569', fontSize: 13 }, address: { color: '#64748b', fontSize: 13 }, notes: { color: '#475569', fontSize: 13, fontStyle: 'italic' }, actions: { flexDirection: 'row', gap: 18, marginTop: 5 }, edit: { color: '#2563eb', fontWeight: '700' }, delete: { color: '#dc2626', fontWeight: '700' } });
