import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ItineraryItem } from '@/lib/itinerary';
import { searchNominatim, type GeocodingResult } from '@/lib/geocoding';
import { ManualLocationMap } from './ManualLocationMap';
const categories = ['spot', 'food', 'hotel', 'flight', 'trail', 'outdoor'];
export function ItineraryItemModal({ visible, item, day, tripId, userId, onClose, onSave, onDelete }: { visible: boolean; item?: ItineraryItem | null; day: number; tripId: string; userId: string; onClose: () => void; onSave: (data: any) => Promise<void>; onDelete?: () => Promise<void> }) {
  const [name, setName] = useState(''); const [address, setAddress] = useState(''); const [time, setTime] = useState(''); const [category, setCategory] = useState('spot'); const [duration, setDuration] = useState(''); const [difficulty, setDifficulty] = useState(''); const [notes, setNotes] = useState(''); const [lat, setLat] = useState<number | null>(null); const [lng, setLng] = useState<number | null>(null); const [results, setResults] = useState<GeocodingResult[]>([]); const [searching, setSearching] = useState(false);
  useEffect(() => { if (visible) { setName(item?.location_name ?? ''); setAddress(item?.address ?? ''); setTime(item?.time ?? ''); setCategory(item?.category ?? 'spot'); setDuration(item?.duration_minutes ? String(item.duration_minutes) : ''); setDifficulty(item?.difficulty ?? ''); setNotes(item?.notes ?? ''); setLat(item?.latitude ?? null); setLng(item?.longitude ?? null); setResults([]); } }, [visible, item]);
  async function search() { if (!address.trim() && !name.trim()) return; setSearching(true); try { setResults(await searchNominatim(address || name)); } catch (e: any) { Alert.alert('搜尋失敗', e?.message ?? '請稍後再試'); } finally { setSearching(false); } }
  async function save() { if (!name.trim()) return Alert.alert('請輸入景點名稱'); await onSave({ ...(item?.id ? { id: item.id } : {}), trip_id: tripId, created_by: item?.created_by ?? userId, day_number: day, location_name: name.trim(), address: address.trim() || null, time: time || null, category, duration_minutes: duration ? Number(duration) : null, difficulty: category === 'trail' ? difficulty || null : null, notes: notes.trim() || null, latitude: lat, longitude: lng }); onClose(); }
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><ScrollView contentContainerStyle={styles.container}><Text style={styles.kicker}>DAY {day}</Text><Text style={styles.title}>{item ? '編輯景點' : '新增景點／活動'}</Text><Text style={styles.label}>景點名稱</Text><TextInput style={styles.input} placeholder="例如：台北 101" value={name} onChangeText={setName} /><Text style={styles.label}>地址與定位</Text><View style={styles.searchRow}><TextInput style={[styles.input, styles.flex]} placeholder="輸入地址後搜尋" value={address} onChangeText={setAddress} /><Pressable style={styles.search} onPress={search}><Text style={styles.white}>{searching ? '…' : '搜尋'}</Text></Pressable></View>{results.map((result) => <Pressable key={result.id} style={styles.result} onPress={() => { setName(name || result.displayName.split(',')[0]); setAddress(result.displayName); setLat(result.latitude); setLng(result.longitude); setResults([]); }}><Text>{result.displayName}</Text></Pressable>)}<Text style={styles.label}>時間</Text><TextInput style={styles.input} placeholder="09:30" value={time} onChangeText={setTime} /><Text style={styles.label}>類別</Text><View style={styles.chips}>{categories.map((value) => <Pressable key={value} onPress={() => setCategory(value)} style={[styles.chip, category === value && styles.selected]}><Text style={category === value ? styles.white : styles.chipText}>{value}</Text></Pressable>)}</View>{category === 'trail' ? <><Text style={styles.label}>步道難度</Text><View style={styles.chips}>{['easy', 'moderate', 'hard'].map((value) => <Pressable key={value} onPress={() => setDifficulty(value)} style={[styles.chip, difficulty === value && styles.selected]}><Text style={difficulty === value ? styles.white : styles.chipText}>{value}</Text></Pressable>)}</View></> : null}<Text style={styles.label}>預估停留時間（分鐘）</Text><TextInput style={styles.input} placeholder="90" keyboardType="number-pad" value={duration} onChangeText={setDuration} /><Text style={styles.label}>備註</Text><TextInput style={[styles.input, styles.notes]} placeholder="想提醒旅伴的事" multiline value={notes} onChangeText={setNotes} /><Text style={styles.label}>地圖 Marker（可拖曳微調）</Text><ManualLocationMap latitude={lat} longitude={lng} onChange={(a, b) => { setLat(a); setLng(b); }} /><View style={styles.actions}><Pressable onPress={onClose}><Text style={styles.cancel}>取消</Text></Pressable>{item && onDelete ? <Pressable onPress={() => Alert.alert('刪除景點', '確定要刪除嗎？', [{ text: '取消' }, { text: '刪除', style: 'destructive', onPress: onDelete }])}><Text style={styles.delete}>刪除</Text></Pressable> : null}<Pressable style={styles.save} onPress={save}><Text style={styles.white}>儲存</Text></Pressable></View></ScrollView></Modal>;
}
const styles = StyleSheet.create({ container: { padding: 24, gap: 10, paddingBottom: 42 }, kicker: { color: '#2563eb', letterSpacing: 1.5, fontWeight: '800' }, title: { fontSize: 28, fontWeight: '800', color: '#0f172a', marginBottom: 5 }, label: { color: '#334155', fontSize: 13, fontWeight: '700', marginTop: 6 }, input: { borderWidth: 1, borderColor: '#dbe2ea', borderRadius: 13, padding: 13, backgroundColor: '#f8fafc', fontSize: 15 }, flex: { flex: 1 }, searchRow: { flexDirection: 'row', gap: 8 }, search: { backgroundColor: '#0f172a', borderRadius: 13, justifyContent: 'center', paddingHorizontal: 15 }, result: { backgroundColor: '#eff6ff', padding: 12, borderRadius: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderRadius: 20, paddingHorizontal: 13, paddingVertical: 9, backgroundColor: '#e2e8f0' }, selected: { backgroundColor: '#2563eb' }, chipText: { color: '#334155' }, notes: { minHeight: 90, textAlignVertical: 'top' }, actions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 20, marginTop: 12 }, cancel: { color: '#475569', fontWeight: '600' }, delete: { color: '#dc2626', fontWeight: '700' }, save: { backgroundColor: '#2563eb', borderRadius: 13, paddingHorizontal: 20, paddingVertical: 13 }, white: { color: 'white', fontWeight: '800' } });
