import React, { useEffect, useState } from 'react';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import type { ItineraryItem } from '@/lib/itinerary';
import { updateItineraryItemsOrder } from '@/lib/itinerary-api';
const icons: Record<string, string> = { spot: '📍', food: '🍜', hotel: '🛏️', flight: '✈️', trail: '🥾', outdoor: '🌿' };
type Props = { items: ItineraryItem[]; onEdit: (item: ItineraryItem) => void; onDelete: (item: ItineraryItem) => void; onReorder?: (items: { id: string; position: number }[]) => Promise<void> };
export function ItineraryTimeline({ items, onEdit, onDelete, onReorder }: Props) {
  const [localItems, setLocalItems] = useState(items); const [dragIndex, setDragIndex] = useState<number | null>(null);
  useEffect(() => setLocalItems(items), [items]);
  async function persist(ordered: ItineraryItem[]) { const payload = ordered.map(({ id, position }) => ({ id, position })); await (onReorder ? onReorder(payload) : updateItineraryItemsOrder(payload)); }
  async function move(from: number, direction: -1 | 1) { const to = from + direction; if (to < 0 || to >= localItems.length) return; const next = [...localItems]; [next[from], next[to]] = [next[to], next[from]]; const ordered = next.map((item, position) => ({ ...item, position })); setLocalItems(ordered); try { await persist(ordered); } catch { setLocalItems(items); } }
  async function drop(to: number) { if (dragIndex === null || dragIndex === to) return setDragIndex(null); const next = [...localItems]; const [moved] = next.splice(dragIndex, 1); next.splice(to, 0, moved); const ordered = next.map((item, position) => ({ ...item, position })); setLocalItems(ordered); setDragIndex(null); try { await persist(ordered); } catch { setLocalItems(items); } }
  if (!localItems.length) return <View style={styles.empty}><Text style={styles.emptyIcon}>🗺️</Text><Text style={styles.emptyText}>這天還沒有安排景點</Text></View>;
  return <View>{localItems.map((item, index) => <View key={item.id} style={styles.row}><View style={styles.rail}>{index < localItems.length - 1 && <View style={styles.line} />}<View style={styles.dot} /></View><View style={styles.card} {...(Platform.OS === 'web' ? { draggable: true, onDragStart: () => setDragIndex(index), onDragOver: (event: any) => event.preventDefault(), onDrop: () => void drop(index) } : {}) as any}><View style={styles.cardHeader}><Text style={styles.time}>{item.time ?? '彈性時間'}</Text><Text style={styles.category}>{icons[item.category] ?? '📌'} {item.category}</Text></View><Text style={styles.name}>{item.location_name}</Text>{item.duration_minutes ? <Text style={styles.duration}>⏱ 停留 {item.duration_minutes} 分鐘</Text> : null}{item.address ? <Text style={styles.address}>{item.address}</Text> : null}{item.notes ? <Text style={styles.notes}>{item.notes}</Text> : null}<View style={styles.actions}><Pressable disabled={index === 0} onPress={() => void move(index, -1)}><Text style={[styles.move, index === 0 && styles.disabled]}>↑ 上移</Text></Pressable><Pressable disabled={index === localItems.length - 1} onPress={() => void move(index, 1)}><Text style={[styles.move, index === localItems.length - 1 && styles.disabled]}>↓ 下移</Text></Pressable><Pressable onPress={() => onEdit(item)}><Text style={styles.edit}>編輯</Text></Pressable><Pressable onPress={() => onDelete(item)}><Text style={styles.delete}>刪除</Text></Pressable></View></View></View>)}</View>;
}
const styles = StyleSheet.create({ empty: { padding: 38, alignItems: 'center', gap: 8 }, emptyIcon: { fontSize: 28 }, emptyText: { color: '#64748b' }, row: { flexDirection: 'row', minHeight: 130 }, rail: { width: 24, alignItems: 'center' }, line: { position: 'absolute', top: 18, bottom: 0, width: 2, backgroundColor: '#dbeafe' }, dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#2563eb', borderWidth: 3, borderColor: '#dbeafe', zIndex: 1 }, card: { flex: 1, marginBottom: 12, padding: 14, borderRadius: 15, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', gap: 5 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, time: { color: '#2563eb', fontWeight: '800' }, category: { color: '#64748b', fontSize: 12 }, name: { color: '#0f172a', fontSize: 18, fontWeight: '800' }, duration: { color: '#475569', fontSize: 13 }, address: { color: '#64748b', fontSize: 13 }, notes: { color: '#475569', fontSize: 13, fontStyle: 'italic' }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginTop: 5 }, move: { color: '#475569', fontWeight: '700' }, disabled: { color: '#cbd5e1' }, edit: { color: '#2563eb', fontWeight: '700' }, delete: { color: '#dc2626', fontWeight: '700' } });
