import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ItineraryItem } from '@/lib/itinerary';
import { searchNominatim, type GeocodingResult } from '@/lib/geocoding';
import { ManualLocationMap } from './ManualLocationMap';

const categories = ['spot', 'food', 'hotel', 'flight', 'trail', 'outdoor'];
export function ItineraryItemModal({ visible, item, day, tripId, userId, onClose, onSave, onDelete }: { visible: boolean; item?: ItineraryItem | null; day: number; tripId: string; userId: string; onClose: () => void; onSave: (data: any) => Promise<void>; onDelete?: () => Promise<void> }) {
  const [name, setName] = useState(''); const [address, setAddress] = useState(''); const [time, setTime] = useState(''); const [category, setCategory] = useState('spot'); const [duration, setDuration] = useState(''); const [difficulty, setDifficulty] = useState(''); const [notes, setNotes] = useState(''); const [lat, setLat] = useState<number | null>(null); const [lng, setLng] = useState<number | null>(null); const [results, setResults] = useState<GeocodingResult[]>([]); const [searching, setSearching] = useState(false);
  useEffect(() => { if (visible) { setName(item?.location_name ?? ''); setAddress(item?.address ?? ''); setTime(item?.time ?? ''); setCategory(item?.category ?? 'spot'); setDuration(item?.duration_minutes ? String(item.duration_minutes) : ''); setDifficulty(item?.difficulty ?? ''); setNotes(item?.notes ?? ''); setLat(item?.latitude ?? null); setLng(item?.longitude ?? null); setResults([]); } }, [visible, item]);
  async function search() { if (!address.trim() && !name.trim()) return; setSearching(true); try { setResults(await searchNominatim(address || name)); } catch (e: any) { Alert.alert('地圖搜尋', e.message); } finally { setSearching(false); } }
  async function save() { if (!name.trim()) return Alert.alert('請輸入景點名稱'); await onSave({ ...(item?.id ? { id: item.id } : {}), trip_id: tripId, created_by: item?.created_by ?? userId, day_number: day, location_name: name.trim(), address: address.trim() || null, time: time || null, category, duration_minutes: duration ? Number(duration) : null, difficulty: category === 'trail' ? difficulty || null : null, notes: notes || null, latitude: lat, longitude: lng }); onClose(); }
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>{item ? '編輯景點' : '新增景點'}</Text><TextInput style={styles.input} placeholder="景點名稱" value={name} onChangeText={setName} /><View style={styles.searchRow}><TextInput style={[styles.input, { flex: 1 }]} placeholder="地址或景點名稱" value={address} onChangeText={setAddress} /><Pressable style={styles.search} onPress={search}><Text style={styles.white}>{searching ? '…' : '搜尋'}</Text></Pressable></View>{results.map((r) => <Pressable key={r.id} style={styles.result} onPress={() => { setName(name || r.displayName.split(',')[0]); setAddress(r.displayName); setLat(r.latitude); setLng(r.longitude); setResults([]); }}><Text>{r.displayName}</Text></Pressable>)}<TextInput style={styles.input} placeholder="時間，例如 09:30" value={time} onChangeText={setTime} /><Text style={styles.label}>景點類型</Text><View style={styles.chips}>{categories.map((c) => <Pressable key={c} onPress={() => setCategory(c)} style={[styles.chip, category === c && styles.selected]}><Text style={category === c ? styles.white : undefined}>{c}</Text></Pressable>)}</View>{category === 'trail' ? <><Text style={styles.label}>步道難度</Text><View style={styles.chips}>{['easy', 'moderate', 'hard'].map((d) => <Pressable key={d} onPress={() => setDifficulty(d)} style={[styles.chip, difficulty === d && styles.selected]}><Text style={difficulty === d ? styles.white : undefined}>{d}</Text></Pressable>)}</View></> : null}<TextInput style={styles.input} placeholder="預估停留時間（分鐘）" keyboardType="number-pad" value={duration} onChangeText={setDuration} /><TextInput style={[styles.input, styles.notes]} placeholder="備註" multiline value={notes} onChangeText={setNotes} /><Text style={styles.label}>可拖曳 Marker 微調座標</Text><ManualLocationMap latitude={lat} longitude={lng} onChange={(a, b) => { setLat(a); setLng(b); }} /><View style={styles.actions}><Pressable onPress={onClose}><Text>取消</Text></Pressable>{item && onDelete ? <Pressable onPress={() => Alert.alert('刪除景點', '確定要刪除嗎？', [{ text: '取消' }, { text: '刪除', style: 'destructive', onPress: async () => { await onDelete(); onClose(); } }])}><Text style={styles.delete}>刪除</Text></Pressable> : null}<Pressable style={styles.save} onPress={save}><Text style={styles.white}>儲存</Text></Pressable></View></ScrollView></Modal>;
}
const styles = StyleSheet.create({ container: { padding: 22, gap: 12, paddingBottom: 40 }, title: { fontSize: 26, fontWeight: '700' }, input: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 10, padding: 12, backgroundColor: 'white' }, searchRow: { flexDirection: 'row', gap: 8, alignItems: 'center' }, search: { backgroundColor: '#475569', borderRadius: 10, padding: 13 }, result: { padding: 10, backgroundColor: '#eef2ff' }, label: { fontWeight: '600' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#e5e7eb', borderRadius: 16 }, selected: { backgroundColor: '#2563eb' }, white: { color: 'white', fontWeight: '700' }, notes: { minHeight: 80, textAlignVertical: 'top' }, actions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 22 }, save: { backgroundColor: '#2563eb', borderRadius: 10, padding: 14 }, delete: { color: '#dc2626' } });
